### 1. operators ==, > <
#### Compare bool, strings

In [1]:
print(True == True)

True


In [2]:
print(True == true) #boolean  values are case sensitive

NameError: name 'true' is not defined

In [3]:
#### Compare integers

In [4]:
if (-5*15) == 75:
    print("True")
else:
    print("False")

False


#### Compare bool to int

In [5]:
print(True == 0)

False


#### Comapre numpy list with integer

In [6]:
import numpy as np
marks = np.array([10,20,30,40])
print("The type of marks is", type(marks) , "and items are", marks, "\n")
print("In comaprisions, we need to use list name and not list itself")
print(marks>10) #results all items of array which are > 10
print(marks>50) #results all items of array which are > 10
print(marks[marks>20])
print("In comaprisions, list compared to integer results an error")
#print([10,20,30,50]>10)

The type of marks is <class 'numpy.ndarray'> and items are [10 20 30 40] 

In comaprisions, we need to use list name and not list itself
[False  True  True  True]
[False False False False]
[30 40]
In comaprisions, list compared to integer results an error


In [7]:
marks = np.

SyntaxError: invalid syntax (<ipython-input-7-14bae2976dfa>, line 1)

### 2. Operators 'and' 'or' 'not'

In [33]:
print(not True)

False


In [35]:
x=4
print(x>3 and x<10)
print (x==3 or x>1)

True
True


### 3. Numpy Boolean Operators: "and, or, not" as built-in methods of numpy

In [37]:
import numpy as np
marks = np.array([60,70,80,90,95,100])
marks

array([ 60,  70,  80,  90,  95, 100])

In [46]:
print(marks>60) 


#print(marks>60 and marks<95) #Check the error by uncommenting
#ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

[False  True  True  True  True  True]


In [43]:
type(print(marks[marks>80])) #Observe the result type its Nonetype

[ 90  95 100]


NoneType

##### Trying to use and operator on numpy array items returns an error. There comes the need of the built-in methods for 
##### logical and logical or and logical not methods

In [54]:
print(marks[marks>60])
print(marks[marks>60] and marks[marks<95]) ##This triggers the need of logical_and logical_or functions

[ 70  80  90  95 100]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

###### logical and

In [8]:
print(marks)
print(np.logical_and(marks<95,marks>60))
print(marks[np.logical_and(marks<95,marks>60)]) 


[10 20 30 40]
[False False False False]
[]


###### logical or

In [61]:
print(marks[np.logical_or(marks<95,marks>60,marks==0)])

[ 60  70  80  90  95 100]


###### logical not

In [66]:
print(marks)
print(np.logical_not(marks<0))
print(marks[np.logical_not(marks<0)])

[ 60  70  80  90  95 100]
[ True  True  True  True  True  True]
[ 60  70  80  90  95 100]


### 4.Operators on dataframe of pandas 

In [74]:
print("Importing csv fle as dataframe")
import pandas as pa
cars = pa.read_csv("mpg.csv",index_col = 0)
#print(cars)
print(cars[model]=='a1')

Importing csv fle as dataframe


NameError: name 'model' is not defined

In [75]:
a=12.25
bool(a)

True

Note: print statement default end of line is \n. but we can define using optional argument example:end=','

In [102]:
enumerate?

True

False

False